// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz-KaCsw6YRPcvc2bYZrnvSj3swiVoMtc',
    appId: '1:292368412038:web:fc97df8dee25a46627d007',
    messagingSenderId: '292368412038',
    projectId: 'kerja-praktek-eef59',
    authDomain: 'kerja-praktek-eef59.firebaseapp.com',
    storageBucket: 'kerja-praktek-eef59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAOrRwYX0B5GZPCBY1hsgjkLav8EW4B14',
    appId: '1:292368412038:android:4bdb179125b7a08927d007',
    messagingSenderId: '292368412038',
    projectId: 'kerja-praktek-eef59',
    storageBucket: 'kerja-praktek-eef59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIkJnxPfu4xmRrpq6LaZgVShcElB-Oz1s',
    appId: '1:292368412038:ios:1a19d868fd7c068e27d007',
    messagingSenderId: '292368412038',
    projectId: 'kerja-praktek-eef59',
    storageBucket: 'kerja-praktek-eef59.appspot.com',
    iosBundleId: 'com.example.kerjaPraktek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIkJnxPfu4xmRrpq6LaZgVShcElB-Oz1s',
    appId: '1:292368412038:ios:703f9043a5e294ef27d007',
    messagingSenderId: '292368412038',
    projectId: 'kerja-praktek-eef59',
    storageBucket: 'kerja-praktek-eef59.appspot.com',
    iosBundleId: 'com.example.kerjaPraktek.RunnerTests',
  );
}
